/* eslint-disable @typescript-eslint/explicit-function-return-type */
import Head from 'next/head'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import React from 'react'

export default function Home () {
  return (
    <React.Fragment>
      <Head>
        <title>Agus | Fullstack Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>

      <Main />

      <About />

      <Skills />

      <Projects />
    </React.Fragment>
  )
}
